spring.application.name=wanda-web
spring.profiles.active=${SPRING_PROFILE}
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

# JWT
api.security.token.secret=${JWT_SECRET}

#CORS
cors.allowed-origins=${ALLOWED_ORIGINS}

# OTel
otel.exporter.otlp.endpoint=${OTEL_ENDPOINT:http}
otel.exporter.otlp.logs.endpoint=${OTEL_ENDPOINT}/v1/logs
otel.exporter.otlp.traces.endpoint=${OTEL_ENDPOINT}/v1/traces
otel.exporter.otlp.metrics.endpoint=${OTEL_ENDPOINT}/v1/metrics
otel.exporter.otlp.protocol=http/protobuf