spring.application.name=wanda-web
spring.profiles.active=dev
spring.jpa.open-in-view=false

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

# JWT
api.security.token.secret=${JWT_SECRET}

#CORS
cors.allowed-origins=${ALLOWED_ORIGINS}